"""Unit tests for zolt data pipeline."""

import json
import os
import tempfile

from zolt.data.curriculum import (
    estimate_code_complexity,
    estimate_token_sequence_complexity,
    sort_by_curriculum,
)
from zolt.data.dataset import PackedSequenceDataset
from zolt.data.distill import generate_synthetic_instance, mix_datasets
from zolt.data.filter_code import (
    compute_textbook_quality_score,
    content_hash,
    filter_jsonl_file,
    is_permissive_license,
    is_target_language,
    passes_quality_heuristics,
    score_anti_patterns,
    score_comments_and_docstrings,
    score_complexity_readability,
    score_test_presence,
)

# --- filter_code Tests ---


def test_permissive_license_accept():
    assert is_permissive_license("MIT")
    assert is_permissive_license("apache-2.0")
    assert is_permissive_license("BSD-3-Clause")


def test_permissive_license_reject():
    assert not is_permissive_license("GPL-3.0")
    assert not is_permissive_license("AGPL-3.0")
    assert not is_permissive_license(None)
    assert not is_permissive_license("")


def test_target_language_accept():
    assert is_target_language("javascript")
    assert is_target_language("TypeScript")
    assert is_target_language("python")
    assert is_target_language("vue")


def test_target_language_reject():
    assert not is_target_language("java")
    assert not is_target_language("ruby")
    assert not is_target_language(None)


def test_quality_heuristics_pass():
    content = "def hello_world():\n    print('Hello, World!')\n" * 10
    assert passes_quality_heuristics(content)


def test_quality_heuristics_fail_short():
    assert not passes_quality_heuristics("x = 1")


def test_quality_heuristics_fail_empty():
    assert not passes_quality_heuristics("")
    assert not passes_quality_heuristics("   \n\n")


def test_content_hash_deterministic():
    content = "const x = 1;"
    assert content_hash(content) == content_hash(content)


def test_content_hash_different():
    assert content_hash("const x = 1;") != content_hash("const x = 2;")


def test_filter_jsonl_file():
    records = [
        {"content": "def foo():\n    return 42\n" * 10, "lang": "python", "license": "mit"},
        {
            "content": "import java.util.List;",
            "lang": "java",
            "license": "mit",
        },  # reject: wrong lang
        {
            "content": "const x = 1;",
            "lang": "javascript",
            "license": "GPL-3.0",
        },  # reject: non-permissive license
        {"content": "   ", "lang": "python", "license": "mit"},  # reject: quality heuristic
        {
            "content": "def foo():\n    return 42\n" * 10,
            "lang": "python",
            "license": "mit",
        },  # reject: duplicate content
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fin:
        for r in records:
            fin.write(json.dumps(r) + "\n")
        input_path = fin.name

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fout:
        output_path = fout.name

    stats = filter_jsonl_file(input_path, output_path)

    assert stats["accepted"] == 1
    assert stats["lang_filtered"] == 1
    assert stats["license_filtered"] == 1
    assert stats["dedup_filtered"] == 1

    os.unlink(input_path)
    os.unlink(output_path)


# --- Textbook Quality Score Heuristic Tests ---


def test_score_comments_and_docstrings():
    well_documented = (
        '"""Module for calculation."""\n'
        "# Helper function for addition\n"
        "def add(a: int, b: int) -> int:\n"
        '    """Return sum of two integers."""\n'
        "    return a + b\n"
    )
    undocumented = "def add(a, b):\n    return a + b\n" * 10
    score_high = score_comments_and_docstrings(well_documented, "python")
    score_low = score_comments_and_docstrings(undocumented, "python")
    assert score_high > score_low


def test_score_test_presence():
    assert score_test_presence("tests/test_service.py", "") == 1.0
    assert score_test_presence("src/service.spec.ts", "") == 1.0
    assert score_test_presence("src/service.py", "import pytest\ndef test_fn(): pass") == 0.85
    assert score_test_presence("src/service.py", "def fn(): pass") == 0.5


def test_score_anti_patterns():
    clean_code = "function solve() {\n  return 42;\n}\n"
    generated_code = "// @generated by protobuf\nconst x = 1;"
    minified_code = "const " + "a" * 700 + "=1;"
    assert score_anti_patterns(clean_code, "src/index.js") == 1.0
    assert score_anti_patterns(generated_code, "src/proto.js") == 0.0
    assert score_anti_patterns(minified_code, "src/bundle.js") == 0.0
    assert score_anti_patterns(clean_code, "node_modules/pkg/index.js") == 0.0


def test_score_complexity_readability():
    clean_structured = (
        "def process(items):\n    for x in items:\n        if x > 0:\n            yield x * 2\n"
    )
    score = score_complexity_readability(clean_structured, "python")
    assert 0.5 <= score <= 1.0


def test_compute_textbook_quality_score():
    high_quality = (
        '"""High quality module."""\n'
        "# Documented algorithm\n"
        "def compute(x: int) -> int:\n"
        '    """Compute square if positive."""\n'
        "    if x > 0:\n"
        "        return x * x\n"
        "    return 0\n"
    )
    score = compute_textbook_quality_score(high_quality, "python", "tests/test_compute.py")
    assert score >= 0.70


def test_filter_jsonl_with_min_quality_score():
    records = [
        # High quality record
        {
            "content": (
                '"""Math service."""\n'
                "# Pure function\n"
                "def add(a: int, b: int) -> int:\n"
                '    """Add two numbers."""\n'
                "    if a > 0 and b > 0:\n"
                "        return a + b\n"
                "    return 0\n"
            ),
            "lang": "python",
            "license": "mit",
            "path": "tests/test_math.py",
        },
        # Low quality generated record
        {
            "content": "// @generated code\nconst x = 1;\n" * 10,
            "lang": "javascript",
            "license": "mit",
            "path": "src/generated.js",
        },
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fin:
        for r in records:
            fin.write(json.dumps(r) + "\n")
        in_path = fin.name

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fout:
        out_path = fout.name

    stats = filter_jsonl_file(in_path, out_path, min_quality_score=0.60)
    assert stats["accepted"] == 1
    assert stats["quality_score_filtered"] == 1

    os.unlink(in_path)
    os.unlink(out_path)


# --- Teacher Distillation Tests ---


def test_distill_data_format_compatible():
    instance = generate_synthetic_instance(
        None, {"lang": "python", "topic": "graphs"}, mock_mode=True
    )
    assert "content" in instance
    assert "lang" in instance
    assert "license" in instance
    assert "<think>" in instance["content"]
    assert "</think>" in instance["content"]


def test_mix_datasets_ratio():
    corpus = [{"content": f"code_{i}", "lang": "python", "license": "mit"} for i in range(80)]
    distilled = [
        {"content": f"distill_{i}", "lang": "python", "license": "synthetic"} for i in range(20)
    ]

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fc:
        for r in corpus:
            fc.write(json.dumps(r) + "\n")
        c_path = fc.name

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fd:
        for r in distilled:
            fd.write(json.dumps(r) + "\n")
        d_path = fd.name

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as fout:
        out_path = fout.name

    stats = mix_datasets([c_path], [d_path], out_path, distill_ratio=0.20)
    assert stats["total"] > 0
    assert 0.15 <= stats["actual_distill_ratio"] <= 0.25

    os.unlink(c_path)
    os.unlink(d_path)
    os.unlink(out_path)


# --- Curriculum Learning Tests ---


def test_curriculum_complexity_scoring():
    simple_code = "x = 1"
    complex_code = (
        "class Router:\n"
        "    def route(self, req):\n"
        "        for pattern in self.routes:\n"
        "            if pattern.matches(req):\n"
        "                try:\n"
        "                    return self.dispatch(pattern, req)\n"
        "                except Exception as e:\n"
        "                    pass\n"
    )
    score_simple = estimate_code_complexity(simple_code)
    score_complex = estimate_code_complexity(complex_code)
    assert score_complex > score_simple

    ordered = sort_by_curriculum([complex_code, simple_code])
    assert ordered[0] == simple_code
    assert ordered[1] == complex_code


def test_packed_dataset_curriculum_ordering():
    simple_seq = {"input_ids": [10, 11, 12]}
    complex_seq = {"input_ids": list(range(100, 200))}

    with tempfile.NamedTemporaryFile(mode="w", suffix=".jsonl", delete=False) as f:
        f.write(json.dumps(complex_seq) + "\n")
        f.write(json.dumps(simple_seq) + "\n")
        f_path = f.name

    ds = PackedSequenceDataset([f_path], max_seq_len=64, curriculum=True, shuffle=False)
    docs = ds._load_documents(f_path)
    sorted_docs = sort_by_curriculum(docs, complexity_fn=estimate_token_sequence_complexity)
    assert len(sorted_docs[0]) < len(sorted_docs[1])

    os.unlink(f_path)


# --- PackedSequenceDataset Tests ---


def test_packed_dataset_basic():
    """Verify that PackedSequenceDataset produces properly shaped batches."""
    import tempfile

    import numpy as np

    tokens = list(range(1, 5001))  # 5000 sequential tokens
    arr = np.array(tokens, dtype=np.int32)

    with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as f:
        arr.tofile(f)
        bin_path = f.name

    dataset = PackedSequenceDataset(
        token_files=[bin_path],
        max_seq_len=128,
        bos_id=1,
        eos_id=2,
        pad_id=0,
        shuffle=False,
    )

    batches = list(dataset)
    assert len(batches) > 0

    for batch in batches:
        assert "input_ids" in batch
        assert "labels" in batch
        assert batch["input_ids"].shape[0] == 128
        assert batch["labels"].shape[0] == 128

    os.unlink(bin_path)
