"""
Data filtering by language, permissive license, quality heuristics, and SHA256 deduplication.
"""
import hashlib
import json
import os
from pathlib import Path
from typing import List, Optional, Set, Generator


# Target programming languages for zolt
TARGET_LANGUAGES = {
    "javascript",
    "typescript",
    "python",
    "vue",
    "tsx",
    "jsx",
    "css",
    "scss",
    "html",
    "markdown",
    "json",
    "yaml",
}

# Permissive license whitelist
PERMISSIVE_LICENSES = {
    "mit",
    "apache-2.0",
    "apache 2.0",
    "bsd-2-clause",
    "bsd-3-clause",
    "isc",
    "unlicense",
    "cc0-1.0",
    "0bsd",
    "wtfpl",
    "artistic-2.0",
    "eupl-1.2",
    "lgpl-2.1",
    "lgpl-3.0",
    "mpl-2.0",
}

# Quality heuristic thresholds
MIN_CONTENT_LEN = 100     # minimum characters
MAX_CONTENT_LEN = 100_000 # maximum characters
MIN_ALPHANUM_RATIO = 0.20  # minimum alphanumeric character ratio


def is_permissive_license(license_str: Optional[str]) -> bool:
    if not license_str:
        return False
    return license_str.lower().strip() in PERMISSIVE_LICENSES


def is_target_language(lang: Optional[str]) -> bool:
    if not lang:
        return False
    return lang.lower().strip() in TARGET_LANGUAGES


def passes_quality_heuristics(content: str) -> bool:
    if not content or not content.strip():
        return False
    if len(content) < MIN_CONTENT_LEN or len(content) > MAX_CONTENT_LEN:
        return False
    alphanum = sum(c.isalnum() for c in content)
    if alphanum / len(content) < MIN_ALPHANUM_RATIO:
        return False
    return True


def score_comments_and_docstrings(content: str, lang: str = "") -> float:
    """Score ratio of comments and docstrings explaining logic."""
    lines = [line.strip() for line in content.split("\n") if line.strip()]
    if not lines:
        return 0.0

    comment_lines = 0
    in_block = False
    for line in lines:
        if line.startswith('"""') or line.startswith("'''") or line.startswith("/*"):
            comment_lines += 1
            if not (line.endswith('"""') or line.endswith("'''") or line.endswith("*/")) or len(line) <= 3:
                in_block = True
            continue
        if in_block:
            comment_lines += 1
            if line.endswith('"""') or line.endswith("'''") or line.endswith("*/"):
                in_block = False
            continue
        if line.startswith("#") or line.startswith("//") or line.startswith("*"):
            comment_lines += 1

    ratio = comment_lines / len(lines)
    if 0.10 <= ratio <= 0.45:
        return 1.0
    elif 0.04 <= ratio < 0.10:
        return 0.7
    elif ratio > 0.45 and ratio <= 0.70:
        return 0.6
    elif ratio > 0.70:
        return 0.3
    else:
        return 0.3


def score_test_presence(path_or_repo: str = "", content: str = "") -> float:
    """Score indicators of test presence in repository structure or module."""
    path_lower = path_or_repo.lower()
    test_path_indicators = ("test_", "_test", "tests/", "__tests__/", "spec.", "spec/", "testing/")
    if any(ind in path_lower for ind in test_path_indicators):
        return 1.0

    test_content_indicators = (
        "import unittest", "import pytest", "from pytest import",
        "describe(", "it(", "test(", "assert ", "expect("
    )
    if any(ind in content for ind in test_content_indicators):
        return 0.85

    return 0.5


def score_anti_patterns(content: str, path: str = "") -> float:
    """Detect generated, minified, or vendored code patterns."""
    path_lower = path.lower()
    vendored_paths = ("vendor/", "node_modules/", "dist/", "build/", "third_party/", ".min.js", ".min.css")
    if any(vp in path_lower for vp in vendored_paths):
        return 0.0

    generated_markers = (
        "@generated", "do not edit", "auto-generated", "sourcemappingurl=",
        "webpackjsonp", "code generated by", "automatically generated"
    )
    content_lower = content.lower()
    if any(marker in content_lower for marker in generated_markers):
        return 0.0

    lines = content.split("\n")
    if any(len(line) > 600 for line in lines):
        return 0.0

    if len(lines) > 0 and (len(content) / len(lines)) > 160:
        return 0.1

    return 1.0


def score_complexity_readability(content: str, lang: str = "") -> float:
    """Score code complexity and structure readability."""
    lines = [line.strip() for line in content.split("\n") if line.strip()]
    if not lines:
        return 0.0

    branch_keywords = (
        "if ", "elif ", "else if ", "for ", "while ",
        "case ", "switch ", "try:", "catch ", "except ",
        "&&", "||"
    )
    branch_count = sum(any(kw in line for kw in branch_keywords) for line in lines)
    branch_ratio = branch_count / len(lines)

    if 0.03 <= branch_ratio <= 0.25:
        branch_score = 1.0
    elif branch_ratio < 0.03:
        branch_score = 0.5
    else:
        branch_score = 0.4

    func_keywords = ("def ", "function ", "=>", "class ")
    func_count = sum(any(kw in line for kw in func_keywords) for line in lines)
    if func_count > 0:
        avg_func_len = len(lines) / func_count
        if 5 <= avg_func_len <= 80:
            func_score = 1.0
        else:
            func_score = 0.6
    else:
        func_score = 0.7

    return 0.5 * branch_score + 0.5 * func_score


def compute_textbook_quality_score(
    content: str,
    lang: str = "",
    path_or_repo: str = "",
) -> float:
    """Compute weighted composite quality score from 0.0 to 1.0."""
    c_score = score_comments_and_docstrings(content, lang=lang)
    t_score = score_test_presence(path_or_repo, content)
    a_score = score_anti_patterns(content, path_or_repo)
    r_score = score_complexity_readability(content, lang=lang)

    composite = 0.30 * c_score + 0.20 * t_score + 0.25 * a_score + 0.25 * r_score
    return round(max(0.0, min(1.0, composite)), 3)


def content_hash(content: str) -> str:
    """Compute SHA256 hash for exact deduplication."""
    return hashlib.sha256(content.encode("utf-8", errors="replace")).hexdigest()


def filter_jsonl_file(
    input_path: str,
    output_path: str,
    seen_hashes: Optional[Set[str]] = None,
    lang_field: str = "lang",
    license_field: str = "license",
    content_field: str = "content",
    path_field: str = "path",
    max_records: Optional[int] = None,
    min_quality_score: float = 0.0,
) -> dict:
    """Filter code JSONL file by language, license, heuristics, quality score, and SHA256."""
    if seen_hashes is None:
        seen_hashes = set()

    stats = {
        "total": 0,
        "lang_filtered": 0,
        "license_filtered": 0,
        "quality_filtered": 0,
        "quality_score_filtered": 0,
        "dedup_filtered": 0,
        "accepted": 0,
    }

    with open(input_path, "r", encoding="utf-8", errors="replace") as fin, \
         open(output_path, "w", encoding="utf-8") as fout:

        for line in fin:
            stats["total"] += 1
            if max_records and stats["total"] > max_records:
                break

            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue

            lang = obj.get(lang_field, "")
            if not is_target_language(lang):
                stats["lang_filtered"] += 1
                continue

            license_str = obj.get(license_field, "")
            if not is_permissive_license(license_str):
                stats["license_filtered"] += 1
                continue

            content = obj.get(content_field, "")
            if not passes_quality_heuristics(content):
                stats["quality_filtered"] += 1
                continue

            file_path = obj.get(path_field, obj.get("repo", ""))
            quality_score = compute_textbook_quality_score(content, lang=lang, path_or_repo=file_path)
            if min_quality_score > 0.0 and quality_score < min_quality_score:
                stats["quality_score_filtered"] += 1
                continue

            h = content_hash(content)
            if h in seen_hashes:
                stats["dedup_filtered"] += 1
                continue

            seen_hashes.add(h)

            out_record = {
                "content": content,
                "lang": lang,
                "license": license_str,
                "quality_score": quality_score,
            }
            fout.write(json.dumps(out_record, ensure_ascii=False) + "\n")
            stats["accepted"] += 1

    return stats


def tokenize_and_save(
    filtered_jsonl: str,
    tokenizer_path: str,
    output_bin: str,
    content_field: str = "content",
    bos_id: int = 1,
    eos_id: int = 2,
):
    """Tokenize filtered JSONL file and save as an int32 binary token array."""
    import numpy as np
    from tokenizers import Tokenizer as HFTokenizer

    tok = HFTokenizer.from_file(tokenizer_path)
    all_tokens = []

    with open(filtered_jsonl, "r") as f:
        for line in f:
            obj = json.loads(line)
            content = obj.get(content_field, "")
            enc = tok.encode(content, add_special_tokens=False)
            all_tokens.append(bos_id)
            all_tokens.extend(enc.ids)
            all_tokens.append(eos_id)

    arr = np.array(all_tokens, dtype=np.int32)
    arr.tofile(output_bin)
    print(f"[zolt-data] Tokenization complete -> {len(arr):,} tokens -> {output_bin}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="zolt Data Filter and Tokenizer")
    parser.add_argument("--input", required=True, help="Input JSONL file")
    parser.add_argument("--output", required=True, help="Output filtered JSONL file")
    parser.add_argument("--tokenizer", default=None, help="Path to zolt tokenizer JSON")
    parser.add_argument("--output_bin", default=None, help="Output int32 .bin token file path")
    parser.add_argument("--min_quality_score", type=float, default=0.0, help="Minimum textbook quality score threshold (0.0 - 1.0)")
    parser.add_argument("--max_records", type=int, default=None)
    args = parser.parse_args()

    print(f"[zolt-data] Filtering {args.input} -> {args.output} (min_quality_score={args.min_quality_score})")
    stats = filter_jsonl_file(
        args.input,
        args.output,
        max_records=args.max_records,
        min_quality_score=args.min_quality_score,
    )
    print(f"[zolt-data] Stats: {json.dumps(stats, indent=2)}")

    if args.tokenizer and args.output_bin:
        tokenize_and_save(args.output, args.tokenizer, args.output_bin)
